# Generated by Django 3.2.7 on 2021-09-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('headline', models.CharField(max_length=150)),
                ('by_who', models.CharField(max_length=60)),
                ('body_text', models.TextField()),
                ('footer', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
