# Generated by Django 3.2.8 on 2021-10-24 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20211024_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_added',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
