# Generated by Django 3.2.8 on 2021-10-24 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_customer_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone_num',
            new_name='phone_number',
        ),
    ]
