# Generated by Django 3.2.8 on 2021-10-24 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_rename_phone_num_customer_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='active',
        ),
    ]
