# Generated by Django 3.2.8 on 2021-10-26 19:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='eyw_transactionref',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
