# Generated by Django 3.2.8 on 2021-11-03 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20211026_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='eyw_transactionref',
        ),
    ]
