# Generated by Django 3.2.8 on 2021-11-03 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_remove_customer_eyw_transactionref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
