# Generated by Django 3.2.8 on 2021-11-03 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20211102_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='eyw_transactionref',
        ),
    ]
