# Generated by Django 3.2.8 on 2021-12-06 04:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='eyw_transactionref',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
