# Generated by Django 3.2.8 on 2021-12-06 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_customer_eyw_transactionref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='eyw_transactionref',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
