# Generated by Django 3.2.7 on 2021-09-26 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
