# Generated by Django 3.2.7 on 2021-09-26 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_auto_20210926_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=True),
        ),
    ]
